apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set
  labels:
    app: my-replica-set
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-pod
      env: dev
  template:
    metadata:
      name: my-pod
      labels:
        app: my-pod
        env: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx
          env:
            - name: MY_ENV
              value: "true"
