apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
  labels:
    app: my-replication-contorller
    env: dev
spec:
  replicas: 2
  selector:
    app: my-pod
    env: dev
  template:
    metadata:
      name: my-pod
      labels:
        app: my-pod
        env: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx
          env:
            - name: MY_ENV
              value: "true"
