apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alpine-test
  name: alpine-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alpine-test
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo hello from running
        image: alpine:latest
        name: alpine
        resources: {}
status: {}
