apiVersion: batch/v1
kind: CronJob
metadata:
  name: vibrant-tokyo
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Welcome to vibrant Tokyo!
          restartPolicy: OnFailure
