apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lisbon
  name: lisbon
spec:
  containers:
  - image: nginx
    name: lisbon
    ports:
      - containerPort: 8080
        protocol: TCP
  - image: busybox
    name: office
    command: ["/bin/sh"]
    args: ["-c", "sleep 10"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
