apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lisbon-deployment
  name: lisbon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lisbon-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: lisbon-deployment
    spec:
      initContainers:
      - image: busybox
        name: init-container
        command: 
          - '/bin/sh'
          - '-c'
          - "echo 'Hello!' >> /var/log/index.html"
        resources: {}
        volumeMounts:
        - mountPath: /var/log/
          name: cache-volume
      containers:
      - image: nginx:1.17.3-alpine
        name: nginx
        resources: {}
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir: {}
