apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-nginx
  name: busybox-nginx
spec:
  containers:
    - command: ["/bin/sh"]
      args: ["-c","while true; do echo 'Hi I am from main container' >> /var/log/index.html; sleep 5; done"]
      image: busybox
      name: busybox-main-container
      resources: {}
      volumeMounts:
      - mountPath: /var/log/
        name: web-page-volume
    - image: nginx
      name: nginx
      resources: {}
      ports:
        - containerPort: 80
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: web-page-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: web-page-volume
    emptyDir: {}
