apiVersion: v1
kind: Pod
metadata:
  name: time-check
  labels:
    app: time-check
    env: dev
spec:
  containers:
    - name: nginx-container
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date)>> /opt/time/time-check.log; sleep $TIME_FREQ;done"]
      env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
      volumeMounts:
        - mountPath: /opt/time
          name: time-check
  restartPolicy: "OnFailure"
  volumes:
    - name: time-check
      emptyDir: {}
